name: Nikolay Nikolov
name: Nikolay Nikolov
url: http://nikolov.me.uk
domain: nikolov.me.uk
author :
  name : Nikolay Nikolov
  email : nikolay12@gmail.com
  twitter : https://twitter.com/NickNikolov2
  linkedin : https://uk.linkedin.com/pub/nikolay-nikolov/8a/261/758
